version: "3"
services:
  web:
    build: .
    image: dev/ellishelp
    volumes:
      - .:/opt/ellishelp:Z
    labels:
      - "traefik.backend=ellishelp"
      - "traefik.frontend.rule=Host:ellishelp.com, www.ellishelp.com"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: dh1proxy_webproxy

